# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mgao/Code/frds/frds/gui/ui_components/ui_files/DataDownloadWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataDownloadWindow(object):
    def setupUi(self, DataDownloadWindow):
        DataDownloadWindow.setObjectName("DataDownloadWindow")
        DataDownloadWindow.resize(723, 554)
        self.centralwidget = QtWidgets.QWidget(DataDownloadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxDatasetsToDownload = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDatasetsToDownload.setObjectName("groupBoxDatasetsToDownload")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBoxDatasetsToDownload)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.groupBoxDatasetsToDownload)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.gridLayout.addWidget(self.groupBoxDatasetsToDownload, 0, 1, 1, 1)
        self.groupBoxDatasetsAvailable = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDatasetsAvailable.setObjectName("groupBoxDatasetsAvailable")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxDatasetsAvailable)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView = QtWidgets.QTreeView(self.groupBoxDatasetsAvailable)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout.addWidget(self.treeView)
        self.gridLayout.addWidget(self.groupBoxDatasetsAvailable, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        DataDownloadWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(DataDownloadWindow)
        self.statusBar.setObjectName("statusBar")
        DataDownloadWindow.setStatusBar(self.statusBar)

        self.retranslateUi(DataDownloadWindow)
        QtCore.QMetaObject.connectSlotsByName(DataDownloadWindow)

    def retranslateUi(self, DataDownloadWindow):
        _translate = QtCore.QCoreApplication.translate
        DataDownloadWindow.setWindowTitle(_translate("DataDownloadWindow", "Data Download"))
        self.groupBoxDatasetsToDownload.setTitle(_translate("DataDownloadWindow", "Datasets to download"))
        self.groupBoxDatasetsAvailable.setTitle(_translate("DataDownloadWindow", "Datasets available"))
