# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/mgao/Code/frds/frds/gui/ui_components/ui_files/ProgressWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressWindow(object):
    def setupUi(self, ProgressWindow):
        ProgressWindow.setObjectName("ProgressWindow")
        ProgressWindow.resize(766, 448)
        self.centralwidget = QtWidgets.QWidget(ProgressWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowserLogs = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserLogs.setObjectName("textBrowserLogs")
        self.gridLayout.addWidget(self.textBrowserLogs, 1, 1, 1, 1)
        self.labelProgresses = QtWidgets.QLabel(self.centralwidget)
        self.labelProgresses.setObjectName("labelProgresses")
        self.gridLayout.addWidget(self.labelProgresses, 0, 0, 1, 1)
        self.labelLogs = QtWidgets.QLabel(self.centralwidget)
        self.labelLogs.setObjectName("labelLogs")
        self.gridLayout.addWidget(self.labelLogs, 0, 1, 1, 1)
        self.listViewProgresses = QtWidgets.QListView(self.centralwidget)
        self.listViewProgresses.setObjectName("listViewProgresses")
        self.gridLayout.addWidget(self.listViewProgresses, 1, 0, 1, 1)
        ProgressWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProgressWindow)
        self.statusbar.setObjectName("statusbar")
        ProgressWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProgressWindow)
        QtCore.QMetaObject.connectSlotsByName(ProgressWindow)

    def retranslateUi(self, ProgressWindow):
        _translate = QtCore.QCoreApplication.translate
        ProgressWindow.setWindowTitle(_translate("ProgressWindow", "Progress Monitor"))
        self.labelProgresses.setText(_translate("ProgressWindow", "Progresses"))
        self.labelLogs.setText(_translate("ProgressWindow", "Logs"))
